language: node_js

node_js:
  - "8.9.4"

branches:
  only:
  - master

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - npx @angular/cli analytics off

install:
  - cd App/
  - npm install

script:
  - npm run build

sudo: false
