language: node_js

node_js:
  - "10.15.3"

branches:
  only:
  - master
  
before_install:
  - npx @angular/cli analytics off

install:
  - cd App/
  - npm install

script:
  - npm run build

sudo: false
